# @package _global_
defaults:
 - dataset: ???
 - model: ???
 - training: ${defaults.0.dataset}/${defaults.1.model}

log:
  dir: null
  backup_code: true
  save_ckpt: true
  save_ckpt_every_n_epochs: 1
  save_summary: true
  save_summary_every_n_steps: 100
