# @package _global_
model:
  name: pointnet2_cls
  resume_path: null
  batch_size: 64

  sa1:
    n_samples: 512
    radius: 0.2
    n_points_per_group: 32
    mlp_out_channels: [64, 64, 128]
  sa2:
    n_samples: 128
    radius: 0.4
    n_points_per_group: 64
    mlp_out_channels: [128, 128, 256]
  sa3:
    n_samples: 1
    radius: null
    n_points_per_group: null
    mlp_out_channels: [256, 512, 1024]

  fc1:
    out_channels: 512
  fc2:
    out_channels: 256
