# @package _global_
model:
  name: pointnet2_seg_msg
  resume_path: null
  batch_size: 64

  sa1:
    n_samples: 1024
    radius: [0.05, 0.1]
    n_points_per_group: [16, 32]
    mlp_out_channels: [[16, 16, 32], [32, 32, 64]]
  sa2:
    n_samples: 256
    radius: [0.1, 0.2]
    n_points_per_group: [16, 32]
    mlp_out_channels: [[64, 64, 128], [64, 96, 128]]
  sa3:
      n_samples: 64
      radius: [0.2, 0.4]
      n_points_per_group: [16, 32]
      mlp_out_channels: [[128, 196, 256], [128, 196, 256]]
  sa4:
    n_samples: 16
    radius: [0.4, 0.8]
    n_points_per_group: [16, 32]
    mlp_out_channels: [[256, 256, 512], [256, 384, 512]]

  fp4:
    mlp_out_channels: [512, 512]
  fp3:
    mlp_out_channels: [512, 512]
  fp2:
    mlp_out_channels: [256, 256]
  fp1:
    mlp_out_channels: [128, 128, 128]
