# @package _global_
model:
  name: pointnet2_seg_ssg
  resume_path: null
  batch_size: 64

  sa1:
    n_samples: 1024
    radius: 0.1
    n_points_per_group: 32
    mlp_out_channels: [32, 32, 64]
  sa2:
    n_samples: 256
    radius: 0.2
    n_points_per_group: 32
    mlp_out_channels: [64, 64, 128]
  sa3:
      n_samples: 64
      radius: 0.4
      n_points_per_group: 32
      mlp_out_channels: [128, 128, 256]
  sa4:
    n_samples: 16
    radius: 0.8
    n_points_per_group: 32
    mlp_out_channels: [256, 256, 512]

  fp4:
    mlp_out_channels: [256, 256]
  fp3:
    mlp_out_channels: [256, 256]
  fp2:
    mlp_out_channels: [256, 128]
  fp1:
    mlp_out_channels: [128, 128, 128]
